// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import CustomAutocompleteController from "./custom_autocomplete_controller"
application.register("custom-autocomplete", CustomAutocompleteController)

import DatetimepickerController from "./datetimepicker_controller"
application.register("datetimepicker", DatetimepickerController)

import FilterController from "./filter_controller"
application.register("filter", FilterController)

import HelloController from "./hello_controller"
application.register("hello", HelloController)

import PaymentModalController from "./payment_modal_controller"
application.register("payment-modal", PaymentModalController)

//import PopperController from "./popper_controller"
//application.register("popper", PopperController)
