// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import CustomAutocompleteController from "./custom_autocomplete_controller"
application.register("custom-autocomplete", CustomAutocompleteController)

import DatetimepickerController from "./datetimepicker_controller"
application.register("datetimepicker", DatetimepickerController)

import DigitGroupingController from "./digit_grouping_controller"
application.register("digit-grouping", DigitGroupingController)

import FilterController from "./filter_controller"
application.register("filter", FilterController)

import FlashController from "./flash_controller"
application.register("flash", FlashController)

import HelloController from "./hello_controller"
application.register("hello", HelloController)

import InvoiceDetailController from "./invoice_detail_controller"
application.register("invoice-detail", InvoiceDetailController)

import PopperController from "./popper_controller"
application.register("popper", PopperController)

// import SidebarController from "./sidebar_controller"
// application.register("sidebar", SidebarController)
